<a href="https://colab.research.google.com/github/R-aryan/Text-Generation-using-RNN/blob/master/Text_generation_using_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text Generation with Neural Networks

In [1]:
# GOOGLE COLLAB USERS ONLY
%tensorflow_version 2.x

TensorFlow 2.x selected.


In this notebook we will create a network that can generate text, here we show it being done character by character. Very awesome write up on this here: http://karpathy.github.io/2015/05/21/rnn-effectiveness/

We organized the process into "steps" so you can easily follow along with your own data sets.

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

In [3]:
tf.__version__

'2.1.0'

In [4]:
plt.figure(figsize=(12,8))

<Figure size 864x576 with 0 Axes>

<Figure size 864x576 with 0 Axes>

## Step 1: The Data

You can grab any free text you want from here: https://www.gutenberg.org/

We'll choose all of shakespeare's works (which we have already downloaded for you), mainly for two reasons:

1. Its a large corpus of text, its usually recommended you have at least a source of 1 million characters total to get realistic text generation.

2. It has a very distinctive style. Since the text data uses old style english and is formatted in the style of a stage play, it will be very obvious to us if the model is able to reproduce similar results.

In [0]:
train_path='/content/drive/My Drive/Custom_Modelling/shakespeare.txt'

In [6]:
#reading the data from the text file
text = open(train_path, 'r').read()
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


### Understanding unique characters

In [7]:
# The unique characters in the file
vocab = sorted(set(text))
print(vocab)
len(vocab)

['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '}']


84

From the above output we can infer that the entire text corpus consists of 84 unique characters.

## Step 2: Text Processing

### Text Vectorization

We know a neural network can't take in the raw string data, we need to assign numbers to each character. Let's create two dictionaries that can go from numeric index to character and character to numeric index.

In [8]:
char_to_ind = {u:i for i, u in enumerate(vocab)}
print(char_to_ind)

{'\n': 0, ' ': 1, '!': 2, '"': 3, '&': 4, "'": 5, '(': 6, ')': 7, ',': 8, '-': 9, '.': 10, '0': 11, '1': 12, '2': 13, '3': 14, '4': 15, '5': 16, '6': 17, '7': 18, '8': 19, '9': 20, ':': 21, ';': 22, '<': 23, '>': 24, '?': 25, 'A': 26, 'B': 27, 'C': 28, 'D': 29, 'E': 30, 'F': 31, 'G': 32, 'H': 33, 'I': 34, 'J': 35, 'K': 36, 'L': 37, 'M': 38, 'N': 39, 'O': 40, 'P': 41, 'Q': 42, 'R': 43, 'S': 44, 'T': 45, 'U': 46, 'V': 47, 'W': 48, 'X': 49, 'Y': 50, 'Z': 51, '[': 52, ']': 53, '_': 54, '`': 55, 'a': 56, 'b': 57, 'c': 58, 'd': 59, 'e': 60, 'f': 61, 'g': 62, 'h': 63, 'i': 64, 'j': 65, 'k': 66, 'l': 67, 'm': 68, 'n': 69, 'o': 70, 'p': 71, 'q': 72, 'r': 73, 's': 74, 't': 75, 'u': 76, 'v': 77, 'w': 78, 'x': 79, 'y': 80, 'z': 81, '|': 82, '}': 83}


In [9]:
ind_to_char = np.array(vocab)
print(ind_to_char)

['\n' ' ' '!' '"' '&' "'" '(' ')' ',' '-' '.' '0' '1' '2' '3' '4' '5' '6'
 '7' '8' '9' ':' ';' '<' '>' '?' 'A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J'
 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z' '[' ']'
 '_' '`' 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p'
 'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z' '|' '}']


In [10]:
encoded_text = np.array([char_to_ind[c] for c in text])
len(encoded_text)

5445609

## We now have a mapping we can use to go back and forth from characters to numerics.

In [11]:
sample = text[:100]
print(sample)


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose mi


In [12]:
#printing the corresponding encoded text of the sample
encoded_text[:100]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64])

## Step 3: Creating Batches

Overall what we are trying to achieve is to have the model predict the next highest probability character given a historical sequence of characters. Its up to us (the user) to choose how long that historic sequence. Too short a sequence and we don't have enough information (e.g. given the letter "a" , what is the next character) , too long a sequence and training will take too long and most likely overfit to sequence characters that are irrelevant to characters farther out. While there is no correct sequence length choice, you should consider the text itself, how long normal phrases are in it, and a reasonable idea of what characters/words are relevant to each other.

In [13]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [14]:
line = "From fairest creatures we desire increase"
print(len(line))

41


In [15]:
part_stanza = """From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,"""

print(len(part_stanza))

131


### Training Sequences

The actual text data will be the text sequence shifted one character forward. For example:

Sequence In: "Hello my nam"
Sequence Out: "ello my name"


We can use the `tf.data.Dataset.from_tensor_slices` function to convert a text vector into a stream of character indices.

In [0]:
seq_len = 120

In [17]:
total_num_seq = len(text)//(seq_len+1)
total_num_seq

45005

In [18]:
# Create Training Sequences
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

for i in char_dataset.take(30):
     print(ind_to_char[i.numpy()])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m


The **batch** method converts these individual character calls into sequences we can feed in as a batch. We use seq_len+1 because of zero indexing. Here is what drop_remainder means:

drop_remainder: (Optional.) A `tf.bool` scalar `tf.Tensor`, representing
    whether the last batch should be dropped in the case it has fewer than
    `batch_size` elements; the default behavior is not to drop the smaller
    batch.


In [19]:
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)
sequences

<BatchDataset shapes: (121,), types: tf.int64>

Now that we have our sequences, we will perform the following steps for each one to create our target text sequences:

1. Grab the input text sequence
2. Assign the target text sequence as the input text sequence shifted by one step forward
3. Group them together as a tuple

In [0]:
def create_seq_targets(seq):
    input_txt = seq[:-1]
    target_txt = seq[1:]
    return input_txt, target_txt

In [21]:
dataset = sequences.map(create_seq_targets)
dataset

<MapDataset shapes: ((120,), (120,)), types: (tf.int64, tf.int64)>

In [22]:
for input_txt, target_txt in  dataset.take(1):
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    # There is an extra whitespace!
    print(''.join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


### Generating training batches

Now that we have the actual sequences, we will create the batches, we want to shuffle these sequences into a random order, so the model doesn't overfit to any section of the text, but can instead generate characters given any seed text.

In [0]:
# Batch size
batch_size = 128

# Buffer size to shuffle the dataset so it doesn't attempt to shuffle
# the entire sequence in memory. Instead, it maintains a buffer in which it shuffles elements
buffer_size = 10000

dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [24]:
dataset

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int64, tf.int64)>

## Step 4: Creating the Model

We will use an LSTM based model with a few extra features, including an embedding layer to start off with and **two** LSTM layers. We based this model architecture off the [DeepMoji](https://deepmoji.mit.edu/) and the original source code can be found [here](https://github.com/bfelbo/DeepMoji).

The embedding layer will serve as the input layer, which essentially creates a lookup table that maps the numbers indices of each character to a vector with "embedding dim" number of dimensions. As you can imagine, the larger this embedding size, the more complex the training. This is similar to the idea behind word2vec, where words are mapped to some n-dimensional space. Embedding before feeding straight into the LSTM usually leads to more realisitic results.

In [0]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension
embed_dim = 64

# Number of RNN units
rnn_neurons = 1026

Now let's create a function that easily adapts to different variables as shown above.

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU
from tensorflow.keras.losses import sparse_categorical_crossentropy

### Setting up Loss Function

For our loss we will use sparse categorical crossentropy, which we can import from Keras. We will also set this as logits=True

In [27]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module tensorflow.python.keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1)



Which is better for accuracy or are they the same? Of course, if you use categorical_crossentropy you use one hot encoding, and if you use sparse_categorical_crossentropy you encode as normal integers. Additionally, when is one better than the other?

https://datascience.stackexchange.com/questions/41921/sparse-categorical-crossentropy-vs-categorical-crossentropy-keras-accuracy

In [0]:
def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [0]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()

    model.add(Embedding(vocab_size, embed_dim,batch_input_shape=[batch_size, None]))

    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))

    # Final Dense Layer to Predict
    model.add(Dense(vocab_size))

    model.compile(optimizer='adam', loss=sparse_cat_loss) 
    
    return model

In [0]:
model = create_model(
  vocab_size = vocab_size,
  embed_dim=embed_dim,
  rnn_neurons=rnn_neurons,
  batch_size=batch_size)

In [31]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (128, None, 64)           5376      
_________________________________________________________________
gru (GRU)                    (128, None, 1026)         3361176   
_________________________________________________________________
dense (Dense)                (128, None, 84)           86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


## Step 5: Training the model

Let's make sure everything is ok with our model before we spend too much time training! Let's pass in a batch to confirm the model currently predicts random characters without any training.



In [32]:
for input_example_batch, target_example_batch in dataset.take(1):

  # Predict off some random batch
  example_batch_predictions = model(input_example_batch)

  # Display the dimensions of the predictions
  print(example_batch_predictions.shape, " <=== (batch_size, sequence_length, vocab_size)")


(128, 120, 84)  <=== (batch_size, sequence_length, vocab_size)


In [33]:
example_batch_predictions

<tf.Tensor: shape=(128, 120, 84), dtype=float32, numpy=
array([[[-3.2002130e-04, -7.1705282e-03, -2.4767045e-03, ...,
          1.8868089e-04, -4.7398070e-03,  2.4511345e-04],
        [ 4.3969555e-04, -7.1102483e-03,  2.4140603e-04, ...,
         -1.3168859e-03,  3.1657014e-03,  6.5145232e-03],
        [-6.9807598e-04,  2.7503411e-03,  3.2602521e-03, ...,
          1.7276234e-03,  9.3627367e-03,  3.2210939e-03],
        ...,
        [ 3.8598286e-04, -2.4779574e-03,  5.7812501e-03, ...,
         -1.3944267e-03, -2.1288865e-03, -3.8362276e-03],
        [-7.5632706e-04,  4.0524057e-05,  5.2492972e-04, ...,
         -3.0178225e-03,  1.9111681e-03, -8.7548571e-04],
        [-5.2537303e-05, -6.8668914e-03,  1.2938050e-04, ...,
         -6.6268141e-04, -4.4343285e-03, -6.5168896e-04]],

       [[-3.2002130e-04, -7.1705282e-03, -2.4767045e-03, ...,
          1.8868089e-04, -4.7398070e-03,  2.4511345e-04],
        [-1.6457601e-03, -5.8216753e-04,  2.7586939e-03, ...,
          1.6530589e-03, -7

In [34]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[ 5],
       [11],
       [53],
       [26],
       [39],
       [68],
       [38],
       [63],
       [12],
       [ 4],
       [80],
       [64],
       [33],
       [44],
       [80],
       [60],
       [35],
       [59],
       [13],
       [31],
       [55],
       [ 0],
       [12],
       [ 3],
       [26],
       [36],
       [ 1],
       [54],
       [44],
       [80],
       [23],
       [15],
       [23],
       [ 4],
       [58],
       [48],
       [48],
       [ 5],
       [51],
       [47],
       [59],
       [22],
       [20],
       [12],
       [17],
       [31],
       [73],
       [25],
       [48],
       [64],
       [ 5],
       [21],
       [69],
       [82],
       [30],
       [39],
       [53],
       [41],
       [61],
       [31],
       [40],
       [39],
       [13],
       [15],
       [57],
       [19],
       [33],
       [ 1],
       [42],
       [25],
       [65],
       [14],
       [47],
   

In [35]:
# Reformat to not be a lists of lists
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()
sampled_indices

array([ 5, 11, 53, 26, 39, 68, 38, 63, 12,  4, 80, 64, 33, 44, 80, 60, 35,
       59, 13, 31, 55,  0, 12,  3, 26, 36,  1, 54, 44, 80, 23, 15, 23,  4,
       58, 48, 48,  5, 51, 47, 59, 22, 20, 12, 17, 31, 73, 25, 48, 64,  5,
       21, 69, 82, 30, 39, 53, 41, 61, 31, 40, 39, 13, 15, 57, 19, 33,  1,
       42, 25, 65, 14, 47, 24, 48, 78, 53, 50,  1, 66, 69, 19,  7, 34, 58,
       80, 40, 17,  6, 13,  7, 49, 65,  7, 50,  8, 15, 74, 62, 78, 42, 78,
       76, 38, 46,  1, 48, 79, 66, 34, 20, 49, 51, 61, 27, 78, 59, 14, 32,
       41])

In [36]:
print("Given the input seq: \n")
print("".join(ind_to_char[input_example_batch[0]]))
print('\n')
print("Next Char Predictions: \n")
print("".join(ind_to_char[sampled_indices ]))


Given the input seq: 

 altitude of his virtue.
  SECOND CITIZEN. What he cannot help in his nature you account a
    vice in him. You must in 


Next Char Predictions: 

'0]ANmMh1&yiHSyeJd2F`
1"AK _Sy<4<&cWW'ZVd;916Fr?Wi':n|EN]PfFON24b8H Q?j3V>Ww]Y kn8)IcyO6(2)Xj)Y,4sgwQwuMU WxkI9XZfBwd3GP


In [37]:
#After confirming the dimensions are working, let's train our network!
epochs = 30
model.fit(dataset,epochs=epochs)
model.save('/content/drive/My Drive/classification_Dataset/shakespeare_gen.h5') 

Train for 351 steps
Epoch 1/30
351/351 [==============================] - 49s 140ms/step - loss: 2.5102
Epoch 2/30
351/351 [==============================] - 50s 142ms/step - loss: 1.7201
Epoch 3/30
351/351 [==============================] - 51s 144ms/step - loss: 1.4545
Epoch 4/30
351/351 [==============================] - 51s 146ms/step - loss: 1.3380
Epoch 5/30
351/351 [==============================] - 51s 147ms/step - loss: 1.2757
Epoch 6/30
351/351 [==============================] - 52s 147ms/step - loss: 1.2360
Epoch 7/30
351/351 [==============================] - 52s 148ms/step - loss: 1.2071
Epoch 8/30
351/351 [==============================] - 51s 147ms/step - loss: 1.1836
Epoch 9/30
351/351 [==============================] - 51s 146ms/step - loss: 1.1636
Epoch 10/30
351/351 [==============================] - 51s 146ms/step - loss: 1.1465
Epoch 11/30
351/351 [==============================] - 52s 147ms/step - loss: 1.1308
Epoch 12/30
351/351 [==============================] -